### ISSUE TITLE
Errors when trying to identify a 11th or 13th chord

### ISSUE THREAD

**Issue by wombatzus** [bspaans/python-mingus#116]
Mingus version 0.6.1
To reproduce:

```
from mingus.containers.note_container import NoteContainer

chord9 = NoteContainer()
for note in ["C", "E", "G", "B", "D-5"]:
    chord9.add_note(note)
print(chord9.determine())        # Succeeds
chord11 = NoteContainer()

try:
    for note in ["C", "E", "G", "B", "D-5", "F-5"]:
        chord11.add_note(note)
    print(chord11.determine())        # Fails: KeyError: "M11"
except Exception as e:
    print(f"Exception: {type(e)}: {e}")

try:
    chord13 = NoteContainer()
    for note in ["C", "E", "G", "B", "D-5", "F-5", "A-5"]:
        chord13.add_note(note)
    print(chord13.determine())        # Fails: TypeError: can only concatenate str (not "NoneType") to str
except Exception as e:
    print(f"Exception: {type(e)}: {e}")
```

**Comment by BonifacioCalindoro** [comment]
9, 11, and 13 chords have a b7, not a natural 7.

And, when playing the 13 chord you usually don't want to add that 11th because of the dissonance with the 3rd. So it shouldn't have the 11th if we were talking about C13 for example.

On the other side, on the 11 chord, the 3rd is usually ommited, but not necessarily.

So:

C9: C, E, G, bB, D

C11: C, (E), G, bB, D, F

C13: C, E, G; bB, D, A

If you keep the B natural, we're talking about Cmaj9, not C9

**Comment by wombatzus** [comment]
Not sure what your point is, regardless of how you want to categorize chords, the bug is that mingus should not blow up just by asking what chord it is.

**Comment by JimboClark** [comment]
I have to agree with the OP here.  Mingus seems to blow up determining really rather vanilla chords:

```
>>> from mingus.core import *
>>> chords.determine(['A','C','E'])
['A minor triad', 'C major sixth, second inversion']
>>> chords.determine(['A','C','E','G'])
['A minor seventh', 'C major sixth, third inversion', 'CM|Am']
>>> chords.determine(['A','C','E','G','B'])
['A minor ninth', 'Em|Am', 'Em|Am7', 'CM7|Am', 'CM7|Am7']
>>> chords.determine(['A','C','E','G','B','D'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jimbl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\mingus\core\chords.py", line 938, in determine
    return determine_extended_chord6(chord, shorthand, no_inversions, no_polychords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jimbl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\mingus\core\chords.py", line 1238, in determine_extended_chord6
    return inversion_exhauster(chord, shorthand, 1, [], [])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jimbl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\mingus\core\chords.py", line 1226, in inversion_exhauster
    return inversion_exhauster(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jimbl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\mingus\core\chords.py", line 1226, in inversion_exhauster
    return inversion_exhauster(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jimbl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\mingus\core\chords.py", line 1226, in inversion_exhauster
    return inversion_exhauster(
           ^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "C:\Users\jimbl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\mingus\core\chords.py", line 1235, in inversion_exhauster
    res.append(r[2] + chord_shorthand_meaning[r[0]] + int_desc(r[1]))
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
>>>
```
