### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by dpawson** [bspaans/python-mingus#15]
html documentation has

>>> interval.measure("C", "D")
2
>>> interval.measure("D", "C")
10

I think it should be 'intervals' (plural)

HTH

**Comment by dpawson** [comment]
Running Python 3.
Input 

|A C# E
|Bb D F
|B D# F#
|C E G
|C# E# G#

Transpose C to F

Traceback (most recent call last):
  File "/files/python/transposer/transposer/transposer.py", line 170, in <module>
    main()
  File "/files/python/transposer/transposer/transposer.py", line 164, in main
    result = transpose_file(file_name, from_key, to_key)
  File "/files/python/transposer/transposer/transposer.py", line 82, in transpose_file
    result += transpose_line(line, direction, to_key)
  File "/files/python/transposer/transposer/transposer.py", line 108, in transpose_line
    return recursive_line_transpose(source_line, source_chords, direction, to_key)
  File "/files/python/transposer/transposer/transposer.py", line 119, in recursive_line_transpose
    recursive_line_transpose(source_line[after_chord_index:], source_chords, direction, to_key)
  File "/files/python/transposer/transposer/transposer.py", line 118, in recursive_line_transpose
    transpose(source_chord, direction, to_key) + \
  File "/files/python/transposer/transposer/transposer.py", line 128, in transpose
    source_index = get_index_from_key(source_chord)
  File "/files/python/transposer/transposer/transposer.py", line 50, in get_index_from_key
    raise Exception("Invalid key: %s" % source_key)
Exception: Invalid key: E#
/docs/2016/piano/billHiltondpawson12:41>
/docs/2016/piano/billHiltondpawson12:41>transpose.sh C F chords.txt
Traceback (most recent call last):
  File "/files/python/transposer/transposer/transposer.py", line 170, in <module>
    main()
  File "/files/python/transposer/transposer/transposer.py", line 164, in main
    result = transpose_file(file_name, from_key, to_key)
  File "/files/python/transposer/transposer/transposer.py", line 82, in transpose_file
    result += transpose_line(line, direction, to_key)
  File "/files/python/transposer/transposer/transposer.py", line 108, in transpose_line
    return recursive_line_transpose(source_line, source_chords, direction, to_key)
  File "/files/python/transposer/transposer/transposer.py", line 119, in recursive_line_transpose
    recursive_line_transpose(source_line[after_chord_index:], source_chords, direction, to_key)
  File "/files/python/transposer/transposer/transposer.py", line 118, in recursive_line_transpose
    transpose(source_chord, direction, to_key) + \
  File "/files/python/transposer/transposer/transposer.py", line 128, in transpose
    source_index = get_index_from_key(source_chord)
  File "/files/python/transposer/transposer/transposer.py", line 50, in get_index_from_key
    raise Exception("Invalid key: %s" % source_key)
Exception: Invalid key: E#

**Comment by GaryMortensen** [comment]
E# is F... perhaps it is restricting it to the note without the sharp.

**Comment by dpawson** [comment]
Yes, that makes sense, though it seems rather harsh to bomb out with the obvious?
Tks.
