### ISSUE TITLE
decoding errors for MIDI_to_Composition call

### ISSUE THREAD

**Issue by yiyizhai** [bspaans/python-mingus#71]
Hi 

I'm playing with the methods in midi_file_in.py and got a encoding/decoding related error:

```
Traceback (most recent call last):
  File "/Users/yiyizhai/anaconda/lib/python3.6/site-packages/mingus/midi/midi_file_in.py", line 182, in parse_midi_file_header
  File "/Users/yiyizhai/anaconda/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 13: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yiyizhai/anaconda/lib/python3.6/site-packages/mingus/midi/midi_file_in.py", line 69, in MIDI_to_Composition
  File "/Users/yiyizhai/anaconda/lib/python3.6/site-packages/mingus/midi/midi_file_in.py", line 379, in parse_midi_file
  File "/Users/yiyizhai/anaconda/lib/python3.6/site-packages/mingus/midi/midi_file_in.py", line 188, in parse_midi_file_header
OSError: Couldn't read from file.
```

This is the midi file I'm trying to covert: https://drive.google.com/file/d/1rEQvAjFjVbnSrTkQfvN5P66TFZEB8lIe/view?usp=sharing

I also tested open the file and read it myself on console:
```
>>> a=open("why.wav.midi", "rb")
>>> a.read(4)
b'MThd'
```
And the output looks right. I'm wondering if you can help me take a look what is the issue here. Thanks!

**Comment by bmsan** [comment]
Are you using the pip version? "pip install mingus" or the version on the master branch?
I had similar issues with the pip version which I started to modify afterwards I saw the same modifications already exist on the master branch.

**Comment by edudobay** [comment]
Hi @yiyizhai and @bmsan! Thanks for making me remember that I hadn't made a release for the latest fixes :) It should work now if you `pip install -U mingus`. Cheers!

https://github.com/bspaans/python-mingus/releases/tag/0.6.1

**Comment by yiyizhai** [comment]
It works! Thanks a lot for the help here
